org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
loader_version_range=[1,)

# Mod Properties
mod_id=lollygag
mod_name=Lollygag
mod_license=MIT
mod_version=1.0.0
mod_group_id=momo.dev.lollygag

# Dependencies
blueprint_version=8.1.0
## Runtime mods
jei_version=19.27.0.343-neoforge
emi_version=1.1.24+1.21.1+neoforge
jade_version=15.10.5+neoforge
## Moonlight
moonlight_lib_version=1.21-2.29.16-neoforge
every_compat_version=1.21-2.11.25-neoforge
## Nexus Lib for Bountiful Fares
nexuslib_version=1.1.4-neoforge
bountiful_fares_version=3.0.8-neoforge
## NML
biolith_version=3.0.10-neoforge
mixed_litter_version=1.2.2
nml_version=1.5.12
## Aether
owolib_version=0.12.15.5-beta.1+1.21
nitrogen_version=1.21.1-1.1.25-neoforge
accessories_version=1.1.0-beta.53+1.21.1
aether_version=1.21.1-1.5.10-neoforge
## Abnormals
environmental_version=5.0.1
incubation_version=5.0.2
allurement_version=5.0.2
cnc_version=3.0.0
gallery_version=2.0.1
autumnity_version=6.0.1
buzzier_bees_version=7.0.1
## Oreganized
multikulti_version=1.21.1-1.2.3
oreganized_version=5.1.2
## Naturalist
geckolib_version=4.9.1-neoforge
naturalist_version=2.0.2+1.21.1-neoforge
